allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  nx: true
minimumReleaseAgeExclude:
  - baseline-browser-mapping@2.10.42
  - esbuild@0.28.1
  - '@babel/core@7.29.1'
overrides:
  '@babel/core@<=7.29.0': ^7.29.1
  esbuild@>=0.27.3 <0.28.1: ^0.28.1
